services:
  mysqldb:
    image: mysql:8
    container_name: mysql_hometask_5and6
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "${MYSQLDB_DOCKER_PORT}", "-u", "${MYSQLDB_USER}", "-p${MYSQLDB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3